# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-26 13:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channelId', models.CharField(max_length=30)),
                ('channelTitle', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=200)),
                ('publishedAt', models.DateField()),
                ('url', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=30)),
                ('videoId', models.CharField(max_length=30)),
            ],
        ),
    ]
